export declare const WALLEX_API_BASE_URL: string;
export declare const WALLEX_WS_URL: string;
export declare const WALLEX_API_KEY_HEADER: string;
export declare const ORDER_RATE_LIMIT_PER_10S: number;
export declare const ORDER_RATE_LIMIT_WINDOW_MS = 10000;
export declare const STALE_PRICE_TIMEOUT_SECONDS: number;
export declare const REST_POLL_INTERVAL_MS: number;
export declare const WS_RECONNECT_INTERVAL_MS = 5000;
export declare const WS_MAX_RECONNECT_ATTEMPTS = 10;
export declare const DEFAULT_GRID_COUNT = 10;
export declare const DEFAULT_MIN_PROFIT_BPS = 10;
export declare const DEFAULT_MAKER_ONLY = true;
export declare const DEFAULT_INVENTORY_MODE = "EXISTING_ONLY";
export declare const DEFAULT_ON_RANGE_EXIT = "PAUSE_KEEP_ORDERS";
export declare const DEFAULT_MAX_BOTS_GLOBAL = 10;
export declare const DEFAULT_MAX_BOTS_PER_SYMBOL = 3;
export declare const DEFAULT_MAX_DAILY_LOSS_PERCENT = 5;
export declare const DEFAULT_MIN_NOTIONAL = 1;
export declare const DEFAULT_BACKTEST_RESOLUTION = "60";
export declare const MAX_BACKTEST_DAYS = 90;
export declare const WS_PING_INTERVAL_MS = 20000;
export declare const WS_RECONNECT_BEFORE_MS: number;
export declare const WS_MAX_PONG_COUNT = 100;
export declare const DEFAULT_PAPER_BALANCES: Record<string, string>;
