import { z } from 'zod';
import { GridType, TradingMode } from './types';
export declare const GridConfigSchema: z.ZodObject<{
    gridType: z.ZodNativeEnum<typeof GridType>;
    lowerPrice: z.ZodString;
    upperPrice: z.ZodString;
    gridCount: z.ZodNumber;
    totalInvestmentQuote: z.ZodOptional<z.ZodString>;
    quotePerGrid: z.ZodOptional<z.ZodString>;
    basePerGrid: z.ZodOptional<z.ZodString>;
    inventoryMode: z.ZodEnum<["EXISTING_ONLY", "AUTO_REBALANCE", "MANUAL"]>;
    makerOnly: z.ZodDefault<z.ZodBoolean>;
    minProfitAfterFeesBps: z.ZodDefault<z.ZodNumber>;
    onRangeExit: z.ZodDefault<z.ZodEnum<["PAUSE_KEEP_ORDERS", "PAUSE_CANCEL_ALL", "STOP_CANCEL_ALL", "RECENTER", "TRAILING"]>>;
    autoRecenter: z.ZodDefault<z.ZodBoolean>;
    recenterThresholdPercent: z.ZodOptional<z.ZodNumber>;
    recenterCooldownMinutes: z.ZodOptional<z.ZodNumber>;
    stopLossPrice: z.ZodOptional<z.ZodString>;
    takeProfitPrice: z.ZodOptional<z.ZodString>;
    maxOpenOrders: z.ZodOptional<z.ZodNumber>;
    maxQuoteExposure: z.ZodOptional<z.ZodString>;
    maxBaseExposure: z.ZodOptional<z.ZodString>;
    dailyLossLimitPercent: z.ZodOptional<z.ZodNumber>;
    allowMarketOrders: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    gridType: GridType;
    lowerPrice: string;
    upperPrice: string;
    gridCount: number;
    inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
    makerOnly: boolean;
    minProfitAfterFeesBps: number;
    onRangeExit: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING";
    autoRecenter: boolean;
    allowMarketOrders: boolean;
    totalInvestmentQuote?: string | undefined;
    quotePerGrid?: string | undefined;
    basePerGrid?: string | undefined;
    recenterThresholdPercent?: number | undefined;
    recenterCooldownMinutes?: number | undefined;
    stopLossPrice?: string | undefined;
    takeProfitPrice?: string | undefined;
    maxOpenOrders?: number | undefined;
    maxQuoteExposure?: string | undefined;
    maxBaseExposure?: string | undefined;
    dailyLossLimitPercent?: number | undefined;
}, {
    gridType: GridType;
    lowerPrice: string;
    upperPrice: string;
    gridCount: number;
    inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
    totalInvestmentQuote?: string | undefined;
    quotePerGrid?: string | undefined;
    basePerGrid?: string | undefined;
    makerOnly?: boolean | undefined;
    minProfitAfterFeesBps?: number | undefined;
    onRangeExit?: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING" | undefined;
    autoRecenter?: boolean | undefined;
    recenterThresholdPercent?: number | undefined;
    recenterCooldownMinutes?: number | undefined;
    stopLossPrice?: string | undefined;
    takeProfitPrice?: string | undefined;
    maxOpenOrders?: number | undefined;
    maxQuoteExposure?: string | undefined;
    maxBaseExposure?: string | undefined;
    dailyLossLimitPercent?: number | undefined;
    allowMarketOrders?: boolean | undefined;
}>;
export declare const CreateBotSchema: z.ZodObject<{
    name: z.ZodString;
    symbol: z.ZodString;
    strategyType: z.ZodDefault<z.ZodLiteral<"GRID">>;
    mode: z.ZodDefault<z.ZodNativeEnum<typeof TradingMode>>;
    exchangeAccountId: z.ZodOptional<z.ZodString>;
    gridConfig: z.ZodObject<{
        gridType: z.ZodNativeEnum<typeof GridType>;
        lowerPrice: z.ZodString;
        upperPrice: z.ZodString;
        gridCount: z.ZodNumber;
        totalInvestmentQuote: z.ZodOptional<z.ZodString>;
        quotePerGrid: z.ZodOptional<z.ZodString>;
        basePerGrid: z.ZodOptional<z.ZodString>;
        inventoryMode: z.ZodEnum<["EXISTING_ONLY", "AUTO_REBALANCE", "MANUAL"]>;
        makerOnly: z.ZodDefault<z.ZodBoolean>;
        minProfitAfterFeesBps: z.ZodDefault<z.ZodNumber>;
        onRangeExit: z.ZodDefault<z.ZodEnum<["PAUSE_KEEP_ORDERS", "PAUSE_CANCEL_ALL", "STOP_CANCEL_ALL", "RECENTER", "TRAILING"]>>;
        autoRecenter: z.ZodDefault<z.ZodBoolean>;
        recenterThresholdPercent: z.ZodOptional<z.ZodNumber>;
        recenterCooldownMinutes: z.ZodOptional<z.ZodNumber>;
        stopLossPrice: z.ZodOptional<z.ZodString>;
        takeProfitPrice: z.ZodOptional<z.ZodString>;
        maxOpenOrders: z.ZodOptional<z.ZodNumber>;
        maxQuoteExposure: z.ZodOptional<z.ZodString>;
        maxBaseExposure: z.ZodOptional<z.ZodString>;
        dailyLossLimitPercent: z.ZodOptional<z.ZodNumber>;
        allowMarketOrders: z.ZodDefault<z.ZodBoolean>;
    }, "strip", z.ZodTypeAny, {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        makerOnly: boolean;
        minProfitAfterFeesBps: number;
        onRangeExit: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING";
        autoRecenter: boolean;
        allowMarketOrders: boolean;
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
    }, {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        makerOnly?: boolean | undefined;
        minProfitAfterFeesBps?: number | undefined;
        onRangeExit?: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING" | undefined;
        autoRecenter?: boolean | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
        allowMarketOrders?: boolean | undefined;
    }>;
    maxQuoteExposure: z.ZodOptional<z.ZodString>;
    maxBaseExposure: z.ZodOptional<z.ZodString>;
    dailyLossLimitPercent: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    symbol: string;
    name: string;
    strategyType: "GRID";
    mode: TradingMode;
    gridConfig: {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        makerOnly: boolean;
        minProfitAfterFeesBps: number;
        onRangeExit: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING";
        autoRecenter: boolean;
        allowMarketOrders: boolean;
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
    };
    maxQuoteExposure?: string | undefined;
    maxBaseExposure?: string | undefined;
    dailyLossLimitPercent?: number | undefined;
    exchangeAccountId?: string | undefined;
}, {
    symbol: string;
    name: string;
    gridConfig: {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        makerOnly?: boolean | undefined;
        minProfitAfterFeesBps?: number | undefined;
        onRangeExit?: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING" | undefined;
        autoRecenter?: boolean | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
        allowMarketOrders?: boolean | undefined;
    };
    maxQuoteExposure?: string | undefined;
    maxBaseExposure?: string | undefined;
    dailyLossLimitPercent?: number | undefined;
    strategyType?: "GRID" | undefined;
    mode?: TradingMode | undefined;
    exchangeAccountId?: string | undefined;
}>;
export declare const UpdateBotSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    gridConfig: z.ZodOptional<z.ZodObject<{
        gridType: z.ZodNativeEnum<typeof GridType>;
        lowerPrice: z.ZodString;
        upperPrice: z.ZodString;
        gridCount: z.ZodNumber;
        totalInvestmentQuote: z.ZodOptional<z.ZodString>;
        quotePerGrid: z.ZodOptional<z.ZodString>;
        basePerGrid: z.ZodOptional<z.ZodString>;
        inventoryMode: z.ZodEnum<["EXISTING_ONLY", "AUTO_REBALANCE", "MANUAL"]>;
        makerOnly: z.ZodDefault<z.ZodBoolean>;
        minProfitAfterFeesBps: z.ZodDefault<z.ZodNumber>;
        onRangeExit: z.ZodDefault<z.ZodEnum<["PAUSE_KEEP_ORDERS", "PAUSE_CANCEL_ALL", "STOP_CANCEL_ALL", "RECENTER", "TRAILING"]>>;
        autoRecenter: z.ZodDefault<z.ZodBoolean>;
        recenterThresholdPercent: z.ZodOptional<z.ZodNumber>;
        recenterCooldownMinutes: z.ZodOptional<z.ZodNumber>;
        stopLossPrice: z.ZodOptional<z.ZodString>;
        takeProfitPrice: z.ZodOptional<z.ZodString>;
        maxOpenOrders: z.ZodOptional<z.ZodNumber>;
        maxQuoteExposure: z.ZodOptional<z.ZodString>;
        maxBaseExposure: z.ZodOptional<z.ZodString>;
        dailyLossLimitPercent: z.ZodOptional<z.ZodNumber>;
        allowMarketOrders: z.ZodDefault<z.ZodBoolean>;
    }, "strip", z.ZodTypeAny, {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        makerOnly: boolean;
        minProfitAfterFeesBps: number;
        onRangeExit: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING";
        autoRecenter: boolean;
        allowMarketOrders: boolean;
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
    }, {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        makerOnly?: boolean | undefined;
        minProfitAfterFeesBps?: number | undefined;
        onRangeExit?: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING" | undefined;
        autoRecenter?: boolean | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
        allowMarketOrders?: boolean | undefined;
    }>>;
    maxQuoteExposure: z.ZodOptional<z.ZodString>;
    maxBaseExposure: z.ZodOptional<z.ZodString>;
    dailyLossLimitPercent: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    maxQuoteExposure?: string | undefined;
    maxBaseExposure?: string | undefined;
    dailyLossLimitPercent?: number | undefined;
    name?: string | undefined;
    gridConfig?: {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        makerOnly: boolean;
        minProfitAfterFeesBps: number;
        onRangeExit: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING";
        autoRecenter: boolean;
        allowMarketOrders: boolean;
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
    } | undefined;
}, {
    maxQuoteExposure?: string | undefined;
    maxBaseExposure?: string | undefined;
    dailyLossLimitPercent?: number | undefined;
    name?: string | undefined;
    gridConfig?: {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        makerOnly?: boolean | undefined;
        minProfitAfterFeesBps?: number | undefined;
        onRangeExit?: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING" | undefined;
        autoRecenter?: boolean | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
        allowMarketOrders?: boolean | undefined;
    } | undefined;
}>;
export declare const LoginSchema: z.ZodObject<{
    email: z.ZodString;
    password: z.ZodString;
}, "strip", z.ZodTypeAny, {
    email: string;
    password: string;
}, {
    email: string;
    password: string;
}>;
export declare const RegisterSchema: z.ZodObject<{
    email: z.ZodString;
    password: z.ZodString;
}, "strip", z.ZodTypeAny, {
    email: string;
    password: string;
}, {
    email: string;
    password: string;
}>;
export declare const CreateBacktestSchema: z.ZodObject<{
    name: z.ZodString;
    symbol: z.ZodString;
    dateFrom: z.ZodString;
    dateTo: z.ZodString;
    resolution: z.ZodString;
    config: z.ZodObject<{
        gridType: z.ZodNativeEnum<typeof GridType>;
        lowerPrice: z.ZodString;
        upperPrice: z.ZodString;
        gridCount: z.ZodNumber;
        totalInvestmentQuote: z.ZodOptional<z.ZodString>;
        quotePerGrid: z.ZodOptional<z.ZodString>;
        basePerGrid: z.ZodOptional<z.ZodString>;
        inventoryMode: z.ZodEnum<["EXISTING_ONLY", "AUTO_REBALANCE", "MANUAL"]>;
        makerOnly: z.ZodDefault<z.ZodBoolean>;
        minProfitAfterFeesBps: z.ZodDefault<z.ZodNumber>;
        onRangeExit: z.ZodDefault<z.ZodEnum<["PAUSE_KEEP_ORDERS", "PAUSE_CANCEL_ALL", "STOP_CANCEL_ALL", "RECENTER", "TRAILING"]>>;
        autoRecenter: z.ZodDefault<z.ZodBoolean>;
        recenterThresholdPercent: z.ZodOptional<z.ZodNumber>;
        recenterCooldownMinutes: z.ZodOptional<z.ZodNumber>;
        stopLossPrice: z.ZodOptional<z.ZodString>;
        takeProfitPrice: z.ZodOptional<z.ZodString>;
        maxOpenOrders: z.ZodOptional<z.ZodNumber>;
        maxQuoteExposure: z.ZodOptional<z.ZodString>;
        maxBaseExposure: z.ZodOptional<z.ZodString>;
        dailyLossLimitPercent: z.ZodOptional<z.ZodNumber>;
        allowMarketOrders: z.ZodDefault<z.ZodBoolean>;
    }, "strip", z.ZodTypeAny, {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        makerOnly: boolean;
        minProfitAfterFeesBps: number;
        onRangeExit: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING";
        autoRecenter: boolean;
        allowMarketOrders: boolean;
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
    }, {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        makerOnly?: boolean | undefined;
        minProfitAfterFeesBps?: number | undefined;
        onRangeExit?: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING" | undefined;
        autoRecenter?: boolean | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
        allowMarketOrders?: boolean | undefined;
    }>;
    initialBalances: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
    feeOverrides: z.ZodOptional<z.ZodObject<{
        makerFeeRate: z.ZodOptional<z.ZodString>;
        takerFeeRate: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        makerFeeRate?: string | undefined;
        takerFeeRate?: string | undefined;
    }, {
        makerFeeRate?: string | undefined;
        takerFeeRate?: string | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    symbol: string;
    name: string;
    dateFrom: string;
    dateTo: string;
    resolution: string;
    config: {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        makerOnly: boolean;
        minProfitAfterFeesBps: number;
        onRangeExit: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING";
        autoRecenter: boolean;
        allowMarketOrders: boolean;
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
    };
    initialBalances?: Record<string, string> | undefined;
    feeOverrides?: {
        makerFeeRate?: string | undefined;
        takerFeeRate?: string | undefined;
    } | undefined;
}, {
    symbol: string;
    name: string;
    dateFrom: string;
    dateTo: string;
    resolution: string;
    config: {
        gridType: GridType;
        lowerPrice: string;
        upperPrice: string;
        gridCount: number;
        inventoryMode: "EXISTING_ONLY" | "AUTO_REBALANCE" | "MANUAL";
        totalInvestmentQuote?: string | undefined;
        quotePerGrid?: string | undefined;
        basePerGrid?: string | undefined;
        makerOnly?: boolean | undefined;
        minProfitAfterFeesBps?: number | undefined;
        onRangeExit?: "PAUSE_KEEP_ORDERS" | "PAUSE_CANCEL_ALL" | "STOP_CANCEL_ALL" | "RECENTER" | "TRAILING" | undefined;
        autoRecenter?: boolean | undefined;
        recenterThresholdPercent?: number | undefined;
        recenterCooldownMinutes?: number | undefined;
        stopLossPrice?: string | undefined;
        takeProfitPrice?: string | undefined;
        maxOpenOrders?: number | undefined;
        maxQuoteExposure?: string | undefined;
        maxBaseExposure?: string | undefined;
        dailyLossLimitPercent?: number | undefined;
        allowMarketOrders?: boolean | undefined;
    };
    initialBalances?: Record<string, string> | undefined;
    feeOverrides?: {
        makerFeeRate?: string | undefined;
        takerFeeRate?: string | undefined;
    } | undefined;
}>;
export type GridConfigInput = z.infer<typeof GridConfigSchema>;
export type CreateBotInput = z.infer<typeof CreateBotSchema>;
export type UpdateBotInput = z.infer<typeof UpdateBotSchema>;
export type LoginInput = z.infer<typeof LoginSchema>;
export type RegisterInput = z.infer<typeof RegisterSchema>;
export type CreateBacktestInput = z.infer<typeof CreateBacktestSchema>;
